export const SET_LOADING = 'SET_LOADING';
export const SET_SKELETON_LOADING = 'SET_SKELETON_LOADING';
export const SHOW_HIDE_TOAST = 'SHOW_HIDE_TOAST';
export const SHOW_HIDE_NOTIFICATION = 'SHOW_HIDE_NOTIFICATION';